CREATE TABLE Board (
   id INT AUTO_INCREMENT PRIMARY KEY,
   brand VARCHAR(20) NOT NULL,
   model VARCHAR(20) NOT NULL,
   volume NUMBER NOT NULL
);

CREATE TABLE Sail (
   id INT AUTO_INCREMENT PRIMARY KEY,
   brand VARCHAR(20) NOT NULL,
   model VARCHAR(20) NOT NULL,
   size NUMBER NOT NULL
);
